#!/usr/bin/env bash
# Is this a git repo?
if [ ! -f ".git/HEAD" ]; then
    echo "No .git/HEAD - cannot identify branch"
    exit 1
fi
BRANCH="$(awk -F/ '{ print $NF }' < .git/HEAD)"

echo "Hit [ENTER] and I'll deploy the latest ${BRANCH} branch of OpenBEL Workbench."
read

if [ "${BRANCH}" == "unstable" ]; then
    BUILD_KEY="browse/OBWUN-BUILD"
elif [ "${BRANCH}" == "stable" ]; then
    BUILD_KEY="browse/OBWST-BUILD"
else
    echo "Don't know where to grab the ${BRANCH} branch!"
    exit 1
fi

ARTIFACT="${BRANCH}-repository.zip"
LATEST="${BUILD_KEY}/latestSuccessful/artifact/JOB1/repository-zip/${ARTIFACT}"
wget --quiet http://dev.selventa.com:9092/${LATEST} || exit 1
echo "Got $(/bin/ls -sh ${ARTIFACT} | awk '{ print $1 }') from Bamboo."

echo -en "Copying... "
scp ${ARTIFACT} testbed:/opt/tomcat/webapps/eclipse/${BRANCH} >/dev/null || exit 1
echo "okay"

echo -en "Extracting... "
ssh testbed "cd /opt/tomcat/webapps/eclipse/${BRANCH} && unzip -oqq $ARTIFACT" || exit 1
echo "okay"

echo -en "Removing artifact... "
ssh testbed "rm /opt/tomcat/webapps/eclipse/${BRANCH}/$ARTIFACT" || exit 1
rm ${ARTIFACT}
echo "okay"

echo "New ${BRANCH} deployed."
