#!/usr/bin/env bash
if [ -z "${BUILD}" ]; then
    echo "BUILD is not set, exiting"
    exit 1
fi
./tools/scripts/repo-ize || exit 1
rm -fr eclipse
git clone --quiet git@github.com:OpenBEL/eclipse.git eclipse
cd eclipse/unstable || exit 1
git rm plugins/* features/* || exit 1
unzip -oqq ../../unstable-repository.zip
git add --all .
git commit -a -m "Promoting build ${BUILD} to live repository"
git push 2>&1

